# USAGE: use this configuration for loading the "web" image (with app.jar) as opposed to 
#  the "web-and-data" image. E.g.
#  'docker compose -f  docker-compose.yml -f docker-compose.web.yml up'

version: '3'

services:
  cbioportal:
    command: /bin/sh -c "rm -rf /cbioportal-webapp/lib/servlet-api-2.5.jar && java -Xms2g -Xmx4g -jar /cbioportal-webapp/app.jar -spring.config.location=cbioportal-webapp/application.properties --authenticate=false --session.service.url=http://cbioportal-session:5001/api/sessions/my_portal/"